version: '3.9'

services:
  edf_processor:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - dev.env
    volumes:
      - ./data/input:/data/input:ro
      - ./data/output:/data/output
